### ISSUE TITLE
Error: Jest: Failed to parse the TypeScript config file /home/diginori/code/ppabam/FlagForFreedom/jest.config.ts

### ISSUE THREAD

**Issue by ppabam** [ppabam/FlagForFreedom#6]
- https://nextjs.org/docs/14/app/building-your-application/testing/jest
```
$ npm test

> fff@24.12.26 test
> jest

Error: Jest: Failed to parse the TypeScript config file /home/diginori/code/ppabam/FlagForFreedom/jest.config.ts
  Error: Jest: 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
Error: Cannot find package 'ts-node' imported from /home/diginori/code/ppabam/FlagForFreedom/node_modules/jest-config/build/readConfigFileAndSetRootDir.js
    at readConfigFileAndSetRootDir (/home/diginori/code/ppabam/FlagForFreedom/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13)
    at async readInitialOptions (/home/diginori/code/ppabam/FlagForFreedom/node_modules/jest-config/build/index.js:403:13)
    at async readConfig (/home/diginori/code/ppabam/FlagForFreedom/node_modules/jest-config/build/index.js:147:48)
    at async readConfigs (/home/diginori/code/ppabam/FlagForFreedom/node_modules/jest-config/build/index.js:424:26)
    at async runCLI (/home/diginori/code/ppabam/FlagForFreedom/node_modules/@jest/core/build/cli/index.js:151:59)
    at async Object.run (/home/diginori/code/ppabam/FlagForFreedom/node_modules/jest-cli/build/run.js:130:37
```

**Comment by ppabam** [comment]
https://stackoverflow.com/questions/71297895/jest-failed-to-parse-the-typescript-config-file?newreg=7bed69576a6f4ce4a28f9a86f3fd82fe

```bash
$ npm install -D ts-node

$ npm test              

> fff@24.12.26 test
> jest

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /home/diginori/code/ppabam/FlagForFreedom
  222 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 222 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
```

**Comment by ppabam** [comment]
- https://github.com/ppabam/FlagForFreedom/tree/npmTestErr
```bash
$ npm test                  

> fff@24.12.26 test
> jest

 FAIL  lib/__tests__/utils.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/diginori/code/ppabam/FlagForFreedom/lib/__tests__/utils.test.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { getEnv } from "../utils";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.732 s
Ran all test suites.
```

**Comment by ppabam** [comment]
# chatgpt

![image](https://github.com/user-attachments/assets/8edb7928-8c66-42f9-aafd-0f8bde8cc6ab)

```bash
$ npm test

> fff@24.12.26 test
> jest

 PASS  lib/__tests__/utils.test.ts
  ✓ returns the correct number from environment variable (2 ms)
  ✓ returns the default value if the environment variable is not set (1 ms)

----------|---------|----------|---------|---------|----------------------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                
----------|---------|----------|---------|---------|----------------------------------
All files |   42.85 |       50 |      25 |   42.85 |                                  
 utils.ts |   42.85 |       50 |      25 |   42.85 | 4-6,8-15,18-29,41-42,48-49,52-56 
----------|---------|----------|---------|---------|----------------------------------
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        3.473 s, estimated 4 s
Ran all test suites.
```

# 해결
- https://github.com/ppabam/FlagForFreedom/tree/npmTesOK

**Comment by ppabam** [comment]
# ㅎ
